version: '3.7'

services:
  app:
    container_name: app
    image: app_image
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
    ports:
      - "9999:9999"

networks:
  app: